### ISSUE TITLE
Time adjustment

### ISSUE THREAD

**Issue by msaglietto** [unode/polypomo#1]
Hey @unode  ... Thanks!  this is what I was just looking for .. 

Do I have to set the time on the config  like ?
```
exec = /path/to/polypomo --worktime 45
```

Because the scroll up and down is not working to add or subtract  time .. even if I run it on the terminal ... 

Sorry I dont know Python and I could not figure out where the time command was 

EDIT:
I figure out it was locked that is why the scroll didnt work so if you fist middle click and then scroll it works  =P

**Comment by unode** [comment]
@msaglietto the timer starts in lock mode by default which means it ignores scrolls. Try middle clicking it to lock/unlock and it should respond to scrolls.

Edit: Glad you found it, only noticed your edit after writing the comment above. Cheers

**Comment by unode** [comment]
FYI: I just changed the default options to accept seconds instead of minutes in all options.
Before `--worktime` and `--breaktime` accepted seconds while `time +` accepted minutes.
