### ISSUE TITLE
Unicode icons not rendering

### ISSUE THREAD

**Issue by ghost** [unode/polypomo#2]
Do I have to integrate a special font in polybar to be able to render the tomato icon? As of now everything is working fine, except the display of the icons.

**Comment by unode** [comment]
Yes. You'll need a font that includes glyphs [`U+1F345`](https://www.compart.com/en/unicode/U+1F345) and [`U+1F3D6`](https://www.compart.com/en/unicode/U+1F3D6).
I'm using https://github.com/stark/siji and https://www.google.com/get/noto/help/emoji/ for most polybar glyphs.

**Comment by ghost** [comment]
Thank you, with noto installed i get a red icon, but now the icon seems to be very very big, although im defining the fontsize in polybar: 
`font-5 = "NotoColorEmoji:sytle=Regular:pixelsize=10"`

**Comment by unode** [comment]
On my system:
```
font-0 = fixed:pixelsize=10;1
font-1 = unifont:fontformat=truetype:size=8:antialias=false;0                                                                                                                                                                                                                    
font-2 = siji:pixelsize=10;1
font-3 = Noto Emoji:scale=15:antialias=false;0
```

**Comment by ghost** [comment]
Thank you, very kind of you to help me :)
