### ISSUE TITLE
No instance is listening error

### ISSUE THREAD

**Issue by Ace-Krypton** [unode/polypomo#5]
when I start polybar I am getting that error, but then it disappears.

**Comment by unode** [comment]
Would you mind sharing your configuration?

I suspect you are starting multiple instances of polypomo. If you do this they will try to kill each other as there can only be one polypomo instance running.

**Comment by Ace-Krypton** [comment]
![Screenshot_2022-01-07_18-46-49](https://user-images.githubusercontent.com/75210504/148585145-6a791846-6465-404b-8bda-209024ddcc72.png)

**Comment by unode** [comment]
The above looks correct.

The message you mentioned appears when polybar is launched and there's no other instance of polypomo running. Is not an error but a warning/information. Everything works normally once the timer is displayed right?

I'll try to clarify the message to make it clearer that it is not a (fatal) error.

**Comment by Ace-Krypton** [comment]
Oh okay thank you, and yes it is not fatal error

**Comment by unode** [comment]
Fixed in 6e2f2c5f2ce9af16b778183f6ff33de121203be8
Thanks for opening the issue and helping me notice this.
