### ISSUE TITLE
TypeError on timer switch.

### ISSUE THREAD

**Issue by zMenta** [unode/polypomo#8]
![image](https://github.com/unode/polypomo/assets/70714721/ca9a4ed8-1165-4105-a267-ab6012a4c274)
The error occurs when the "tomato" timer is counting and I execute `polypomo end`. 
When the "tomato" timer is paused, the error don't popup and just changes to the "break" timer

**Comment by unode** [comment]
Can you provide a complete traceback? The full error message, including which line it originates from.
I'm afraid your bug report isn't actionable as-is.

**Comment by zMenta** [comment]
How can I execute the module and receive the full traceback? 
Tried running the command  in terminal but no output was provided from executing the command, only on the polybar label.

Tried running `./polypomo end`

**Comment by unode** [comment]
You will need to stop polybar, or remove polypomo from it. Then make sure no `polypomo` process is running on your user/system.
Once you have cleared this out, on a new terminal run `./polypomo` and from a second terminal you should be able to run `./polypomo end`. The error should then appear in the first terminal.

**Comment by zMenta** [comment]
Thank you for explaining it to me.

After running:
1. `./polypomo`
2. `./polypomo toggle`
3.  `./polypomo end`

I receive the following error:

```Traceback (most recent call last):
  File "/home/menta/.config/polybar/modules/./polypomo", line 415, in <module>
    main()
  File "/home/menta/.config/polybar/modules/./polypomo", line 411, in main
    args.func(args)
  File "/home/menta/.config/polybar/modules/./polypomo", line 290, in action_display
    check_actions(sock, status)
  File "/home/menta/.config/polybar/modules/./polypomo", line 269, in check_actions
    status.next_timer()
  File "/home/menta/.config/polybar/modules/./polypomo", line 147, in next_timer
    self.save()  # save before switching if toggle didn't get called
    ^^^^^^^^^^^
  File "/home/menta/.config/polybar/modules/./polypomo", line 156, in save
    with setup_conn(self.saveto) as conn:
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/menta/.config/polybar/modules/./polypomo", line 176, in setup_conn
    conn = sqlite3.connect(path)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
```


*Note*: It only happens when the "tomato" timer is running and not paused. With the "break" timer if I just call `polypono end` it just switches to the "tomato" timer without any errors, even if the timer is unpaused.
But If I run `polypomo end` when the "tomato" timer is stopped / paused, it switches to the "break" timer as expected.

**Comment by unode** [comment]
You seem to be running an outdated version of polypomo.
Can you update to the latest and try again?

**Comment by imenyoo2** [comment]
the issue is in the `save` method, `saveto` is not provided, i opened a pull request

**Comment by unode** [comment]
I couldn't reproduce it from my side yesterday. Today I was able.

Thanks @imenyoo2 and @zMenta for the patch and the bug report.
